### ISSUE TITLE
quic-go call args error

### ISSUE THREAD

**Issue by chaosong** [liudanking/quic-proxy#1]
~/g/s/g/l/quic-proxy ❯❯❯ go get -u github.com/liudanking/quic-proxy/qpclient                                                                                                     

# github.com/liudanking/quic-proxy/common
common/net.go:46:16: too many arguments in call to sess.Close
        have (error)
        want ()
common/net.go:105:16: too many arguments in call to qd.sess.Close
        have (error)
        want ()

**Comment by dmat93** [comment]
edit _common/net.go_ file as the error suggests: go to line 46 and 105 and modify the line in order to have 

`qd.sess.Close()`

instead of

`qd.sess.Close(err)`

then go to the qpclient folder and run

`go build` 

same in the qpserver folder
