### ISSUE TITLE
type quic.Session has no field or method Close

### ISSUE THREAD

**Issue by linzj** [liudanking/quic-proxy#10]
go/src/github.com/liudanking/quic-proxy/common/net.go:51:10: sess.Close undefined (type quic.Session has no field or method Close)
go/src/github.com/liudanking/quic-proxy/common/net.go:113:10: qd.sess.Close undefined (type quic.Session has no field or method Close)

**Comment by liudanking** [comment]
fixed.

**Comment by lyyx5858** [comment]
me too, how to solve this?
