### ISSUE TITLE
Usage with Chrome

### ISSUE THREAD

**Issue by Niek** [liudanking/quic-proxy#14]
The image in the README is not loading for me, can you explain how to use this with Chrome? I tried `--proxy-server="quic://localhost:3443"` but that results in a `ERR_QUIC_PROTOCOL_ERROR` error.

**Comment by Niek** [comment]
Doing a bit more testing, I understand now that the typical usage is to start the `qpclient` executable and connect Chrome to the locally created HTTP proxy.

However, it would be nicer of course if Chrome can connect directly to `qpserver` using the `quic://` protocol. Is this feature planned? It looks to me like it just needs some small tweaks.

**Comment by liudanking** [comment]
Nice suggestion, but based on the design purpose of this project, I am afraid that this feature is not on my plan for quic protocol is not wildly supported.
