### ISSUE TITLE
不稳定啊

### ISSUE THREAD

**Issue by luckypoem** [liudanking/quic-proxy#5]
远没有https://github.com/liudanking/socks5_proxy 稳定。
能改进一下吗

**Comment by liudanking** [comment]
可以的话帮忙测试下最新版的情况

**Comment by skyred** [comment]
我把服务器端和客户端分别在docker里运行。但是，客户端一直似乎收不到浏览器转来的请求，下面是客户端log:
````
root@813953fec893:/go# go get -u github.com/liudanking/quic-proxy/qpclient
root@813953fec893:/go# qpclient -v -k -proxy http://xxxxxxxxxxxxx:3443 -l 127.0.0.1:18080 -auth username:password
2019-11-10 11:39:36 DEBG goroutine:1/1 main.go main.main:15 ▶ client
2019-11-10 11:39:36 INFO goroutine:1/1 main.go main.main:66 ▶ start serving 127.0.0.1:18080
````

这个 `-l` 有什么限制吗？目前还没想到要从哪里debug.

**Comment by liudanking** [comment]
> 我把服务器端和客户端分别在docker里运行。但是，客户端一直似乎收不到浏览器转来的请求，下面是客户端log:
> 
> ```
> root@813953fec893:/go# go get -u github.com/liudanking/quic-proxy/qpclient
> root@813953fec893:/go# qpclient -v -k -proxy http://xxxxxxxxxxxxx:3443 -l 127.0.0.1:18080 -auth username:password
> 2019-11-10 11:39:36 DEBG goroutine:1/1 main.go main.main:15 ▶ client
> 2019-11-10 11:39:36 INFO goroutine:1/1 main.go main.main:66 ▶ start serving 127.0.0.1:18080
> ```
> 
> 这个 `-l` 有什么限制吗？目前还没想到要从哪里debug.

docker有做端口映射吗？
